"""empty message

Revision ID: 5c9f71906a93
Revises: 4605fa1cbe47
Create Date: 2025-11-16 15:14:33.202794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9f71906a93'
down_revision = '4605fa1cbe47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('check_out_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('cart_expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('check_out_time', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('check_in_time')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('cart_expires_at')
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('experience_time')

    # ### end Alembic commands ###
