"""empty message

Revision ID: c92a78fd1a22
Revises: 377f79565771
Create Date: 2025-11-16 20:59:23.898397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92a78fd1a22'
down_revision = '377f79565771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('available_spots', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'date', name='_experience_date_uc')
    )
    with op.batch_alter_table('experience_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_availability_date'))

    op.drop_table('experience_availability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_availability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('available_spots', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], name=op.f('experience_availability_experience_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('experience_availability_pkey')),
    sa.UniqueConstraint('experience_id', 'date', name=op.f('_experience_date_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('experience_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_availability_date'), ['date'], unique=False)

    op.drop_table('booking_items')
    # ### end Alembic commands ###
